# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Sasuke
description: "Un Espacio abierto e interactivo, dedicado a la tecnologia"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: https://williamgavidia.github.io
baseurl: ""

google_analytics: UA-XXXXXXXX-X
repo: https://github.com/williamgavidia/williamgavidia.github.io
disqus_shortname: "williamgavidia"
disqus_site_shortname: "williamgavidia"

# Author settings
author:
  name      : Wuilliam Gavidia
  job       : Ing. en Informatica
  bio       : "Alegre, Confiado, Creativo"
  thumb     : /images/author.jpg
  email     : zerpaw@gmail.com
  github    : https://github.com/williamgavidia
  twitter   : https://twitter.com/Wzerpa_g
  facebook  : https://www.facebook.com/wgavidia
  linkedin  : https://linkedin.com/in/williamgavidia

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
